### ISSUE TITLE
Translation-repon käyttöönotto nexteillä

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-translations#10]
Käyttöönotto vaatii ainakin vielä seuraavat toimenpiteet:

- [ ] yarnin asennus
- [x] käännöstiedostojen symlinkkaus build-skriptiin
- [x] käännöstiedostojen ajo build-skriptiin

**Comment by lmstrand** [comment]
./translate install, jota käytämme käännösten asentamiseen po-tiedostoista ei käytä yarnia joten sitä ei tarvitse asentaa nexteille.
