### ISSUE TITLE
Yksiselitteinen ilmaisu varauksen keskeytyksen viimeiselle voimassaolopäivälle

### ISSUE THREAD

**Issue by rakkyllo** [KohaSuomi/Koha-translations#19]
### Kehitysehdotukseni

Vaskissa on saatu henkilökunnalta palautetta siitä, miten Kohassa ilmaistaan varauksen keskeytyksen viimeinen voimassaolopäivä. Tällä hetkellä teksti on muotoa "Varaus on keskeytetty tähän päivämäärään 01.11.2023 asti". Siitä ei siis yksiselitteisesti voi päätellä, että onko varaus vielä keskeytettynä 1.11.2023 vai aktivoituuko se jo sinä päivänä.

Laitoimme Vaskin verkkokirjastoon tiedon muotoon "Keskeytetty. Keskeytyksen viimeinen voimassaolopäivä 1.11.2023", jolloin se on yksiselitteinen. Kyseinen muoto on vain kuusi merkkiä pidempi kuin aiempi.

Voidaanko tästä keskustella ja, jos se on mahdollista, muuttaa kieliasua?

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 22.8.2023: Muutetaan käännösteknisistä syistä loppu muotoon "ja viimeinen voimassaolopäivä on %s".

**Comment by AnneliO** [comment]
Jos muutos on ok, niin suljetko Roosa tiketin? :)

**Comment by rakkyllo** [comment]
Hei, joo kyllä tämä passaa :) Suljen tiketin. Kiitos!

**Comment by MikkoLiimatainen** [comment]
Avaan tiketin uudelleen, koska tämä käännös ei nyt kuvaa oikein toimintoa, sillä valittua päivämäärää ei lasketakaan keskeytykseen mukaan. Varauksen keskeytys on tietokantataulussa valittuun päivään klo 00:00:00 asti voimassa, joten todellisuudessa keskeytys päättyy valittua edelliseen päivään.

Olisiko parempi korjata toiminto niin, että valittu päivämäärä on keskeytyksen viimeinen voimassaolopäivä, vai pyritäänkö muotoilemaan tekstit niin, että siitä käy ilmi, mitä päivämäärävalinta tekee? Käytetäänkö viimeisen voimassaolopäivän sijaan esimerkiksi varauksen aktivointipäivää?

Millä tavalla muut ajattelevat tuon päivämäärävalinnan? Mitä siinä halutaan valita? Valitaanko keskeytyksen viimeinen voimassaolopäivä, vai varauksen aktivointipäivä?

**Comment by atarnus** [comment]
Kirjaston asiakkaan roolissa minusta olisi mielekästä että tuossa on nimenomaan se varauksen uudeelleen aktivoitumisen päivä (eli 1. päivä jolloin olisin valmis noutamaan tuon kyseisen varauksen), eli kuten se nyt teknisesti onkin kyseisen vrk:n alussa. Vaihtaisin vain käännöksen vastaamaan tätä (ja huomioisin tietysti että selite on yhdenmukainen kaikissa näkymissä).

Tällä olisi myös se hyvä puoli, ettei tuota ajastusta tarvisi alkaa muuttamaan.

**Comment by AnneliO** [comment]
Löysin Kohan puolelta tällaiset käännökset liittyen varausten keskeytykseen ja niiden jatkamiseen. Ylimmäisenä englanniksi, sen alla nykyinen käännös ja alimmaisena ehdotettu uusi käännös.

**until %s**
ja viimeinen voimassaolopäivä on %s
ja varaus aktivoituu %s

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/03cd083c-f714-433c-ad6e-5c4547de97c8)

---

**until**
tähän päivämäärään asti
ja aktivoi varaukset

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/c8941659-3719-4300-b9ec-ea383113aafb)

---

**Suspend until**
Keskeytä tähän saakka
Keskeytä ja aktivoi valittuna päivänä

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/905c0a5c-4f91-4ae2-b529-0d4487a69438)

---

**Suspend on**
Keskeytetty tähän saakka
Keskeytetty, aktivoituu

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/b90db2c6-5e4d-47d1-8e9e-e06307e92256)

---

**Suspend until:**
Keskeytä varaus tähän saakka:
Keskeytä varaus ja aktivoi se:

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/5eeb786e-5e70-4fc9-b021-8336f02de112)

---

**Resume**
Jatka
Aktivoi

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/70ef223b-eeeb-4655-a089-a48e5be995bd)
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/1aff58fe-cd5d-49a7-b797-f99fb57cde4e)

---

**Resume all suspended holds**
Jatka kaikki keskeytetyt varaukset
Aktivoi kaikki keskeytetyt varaukset

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/33121325/8876f63c-ed22-44ec-b62d-16cf8679805a)

---

**Unsuspend %s** 
Jatka %s 
Aktivoi %s 

Tämä lienee joko asiakkaan tiedoissa tai tietueen varausjonossa oleva Jatka-nappi.

**Comment by AnneliO** [comment]
Seuraavaan päivitykseen tulee seuraavanlaiset muutokset:

until
tähän päivämäärään asti -> ja aktivoi varaukset

Resume all suspended holds
Jatka kaikki keskeytetyt varaukset -> Aktivoi kaikki keskeytetyt varaukset

Unsuspend %s
Jatka %s -> Aktivoi %s

until %s
ja viimeinen voimassaolopäivä on %s -> ja varaus aktivoituu %s

Suspend until
Keskeytä tähän saakka -> Keskeytä ja aktivoi valittuna päivänä

Suspend until:
Keskeytä varaus tähän saakka: -> Keskeytä varaus ja aktivoi se:

Suspend on
Keskeytetty tähän saakka -> Keskeytetty, aktivoituu

Resume
Jatka -> Aktivoi

**Comment by AnneliO** [comment]
Jos tämä on nyt ok, niin tiketin voisi sulkea. :)

**Comment by MikkoLiimatainen** [comment]
Juu, suljetaanpa tämä.
