### ISSUE TITLE
Käännöspyyntö: Itsepalvelulainaus

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha-translations#20]
### Tukipyyntö

Voisiko nämä kuvissa näkyvät itsepalvelulainaukseen liittyvät englanninkieliset tekstit kääntää?

![MicrosoftTeams-image(1)](https://github.com/KohaSuomi/Koha/assets/99409279/6bf589aa-8bbd-42b0-91e2-03b87f3f63fa)
![MicrosoftTeams-image](https://github.com/KohaSuomi/Koha/assets/99409279/a9f67a78-d31a-4e8c-b7a0-9b7ef7b9b1d2)

**Comment by AnneliO** [comment]
Tarkistan, löytyykö noita po-tiedostoista.

**Comment by AnneliO** [comment]
Nämä löytyivät fi-FI-opac-bootstrap.po-tiedostosta.

Item checked in  -> Teos palautettu (oli Item checked in)

ja 

"Please enter barcode:" -> Lue viivakoodi (oli Syötä kirjastokortin numero, eli periaatteessa käännös oli, joten katsotaan, onko muutoksella vaikutusta)

Viedään tuotantoon seuraavassa päivityksessä.

**Comment by IrinaHalminen** [comment]
On testattu tuotannossa ja kaikki kunnossa, kiitos!
