### ISSUE TITLE
Access your background jobs -tekstin käännös

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha-translations#23]
### Tukipyyntö

Joillain käyttäjillä Kohan etusivulla näkyvä Access your background jobs -teksti on nyt käännettynä Tausta-ajojen käyttö. Parempi voisi olla esim. Tausta-ajosi.

Toiminto on tarkoitettu käyttäjille, jotka tekevät eräajoja, mutta joilla ei ole manage_background_jobs-käyttöoikeutta. Tämän avulla he pääsevät näkemään omat eräajoista syntyneet taustatyöt ja esim. voivat seurata niiden valmistumista.

Toiminto ei näy käyttäjille, joilla on manage_background_jobs-käyttöoikeus.

**Comment by AnneliO** [comment]
Käännös muutettu muotoon Taustatyösi. Tuohon muotoon siksi, että toiminnosta on käytetty taustatyö-termiä muualla käännöksissä. :)

Muutos tulee tuotantoon seuraavassa päivityksessä.

**Comment by AnneliO** [comment]
Tuomas, jos tämä on ok, niin suljetko tiketin? :)

**Comment by Tuomas-Kyyti** [comment]
Kunnossa.
