### ISSUE TITLE
Veloitusaika muuttuu automaattisesti laina- ja maksusäännöissä muita saman rivin sääntöjä muokatessa

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha-translations#24]
### Mikä vikana?

Kun laina- ja maksusäännöissä alkaa muokata jotain yksittäistä sääntöä, ko. nidetyypin Veloitusajankohta-sarakkeessa pudotusvalikon valinta hyppää oletuksena kohtaan "Aikavälin loppupäivä". Meillä velotusaika on pääsääntöisesti seitsemän päivän jakson alku, joten mitä tahansa sääntöä muokatessa pitää lisäksi käydä ennen tallentamista palauttamassa pudotusvalikon valinta takaisin kohtaan "aikavälin alku", jotta se ei tallennu väärin. 

### Mitä pitäisi tapahtua

Ideaalitilanteessa jo tallennettu valinta ei vaihtuisi enää muuksi kuin manuaalisesti sitä muuttamalla.

**Comment by emta001** [comment]
En saa toistettua tätä omilla testeilläni. Auttaisiko selaimen välimuistin ja evästeiden tyhjäys?

**Comment by ElinaUotila** [comment]
Ei näyttänyt olevan vaikutusta välimuistin ja evästeiden tyhjennyksellä. Edelleen pomppaa tuo "Aikavälin loppupäivä" tuonne valinnaksi, kun lähden muokkaamaan uutta riviä. 

![laina- ja maksusäännöt17082023](https://github.com/KohaSuomi/Koha/assets/112157980/f641390b-f3c0-43ea-99b0-34fddfec48e6)

**Comment by emta001** [comment]
Kuulemma näin on käynyt myös jollain muulla testillä. Tutkaillaanpa siis uudestaan mitä tässä käy.

**Comment by emta001** [comment]
Äsh unohdin kommentoida tähän, että korjaus on viety testeille.

**Comment by pknuuti** [comment]
Vaarassa on asetuksena Aikavälin loppupäivä. Vaihdoin asetuksen Aikavälin aluksi ja tallensin. Sen jälkeen menin muokkaamaan samaa riviä ja asetuksena oli jälleen loppupäivä. Eli ei se pysy, kun sitä muokataan.
Missä tämä oletus on määritelty? En ainakaan löydä sille asetusta.

**Comment by ElinaUotila** [comment]
Ehdin itse vasta eilen testaamaan, enkä saanut tätä vieläkään toimimaan oikein testillä (enkä tuotannossa, mutta siellä en vielä sen odottanutkaan toimivan).

**Comment by LeenaKinnunen** [comment]
Lapissa toimii samoin, miten Päivi oli Vaarassa kertonut toimivan. Eli ei pysy tallennus, vaan tarjoaa aina veloituksen loppupäivää huolimatta edellisestä valinnasta ja tallennuksesta.

**Comment by iinaniemi** [comment]
Sama homma Vaskissa. Tarjoaa aina veloituksen loppupäivää.

**Comment by ReettaSiili** [comment]
Nyt Siilin testissä iltapäivällä testasessa englannin kielellä säilyttää mun mielestä start of intervalin uudelleen tallentaessa, suomen kielisellä puolella vaihtaa end of intervaliksi. Siilissä normaalisti kyllä käytössä Jakson loppu kuten Vaarassa.

**Comment by pknuuti** [comment]
Hyvä huomio, Reetta! Näin toimii Vaarankin testillä eli englanninkielisenä se pysyy valinnassaan.

**Comment by ElinaUotila** [comment]
Meilläkin valinta pysyy, kun kieli on englanti.

**Comment by emta001** [comment]
Muutos on viety tuotantoon edellisessä päivityksessä. Ainakaan valituksia ei ole meille asti kuulunut, joten tiketin voisi sulkea?

**Comment by ElinaUotila** [comment]
Testasin äsken tuotannossa, ja englanniksi käytettäessä toimii tosiaan niin kuin halutaan, suomeksi sitten eri tavalla. Mutta pääasia, että toimii.

**Comment by emta001** [comment]
Avvan tän uudestaan kunnes saadan tämä toimimaan myös suomeksi.

**Comment by emta001** [comment]
> Testasin äsken tuotannossa, ja englanniksi käytettäessä toimii tosiaan niin kuin halutaan, suomeksi sitten eri tavalla. Mutta pääasia, että toimii.

Eivät toimi suomeksi, koska tuon säännön arvoissa on eri käännökset. Tallennetun säännön arvo on joko "Jakson alku" tai "Jakson loppu". Mutta vastaavan säännön valinnassa on käytetty käännöksiä "Aikavälin alku" tai "Aikavälin loppupäivä". Koha ei osaa täsmäyttää näitä keskenään ja sen vuoksi arvo jää kopioimatta. 

![Screenshot from 2023-09-26 14-41-40](https://github.com/KohaSuomi/Koha/assets/37581745/97d3e922-e514-4179-8f60-568ad6e56ca0)

Käännöksen kun korjaa, niin tuon pitäisi ruveta toimimaan myös suomeksi.

**Comment by AnneliO** [comment]
Uudet käännökset viety sekä Koha-translations -repoon että yhteisön Pootleen.

Tulee näkyville seuraavassa päivityksessä.

**Comment by emta001** [comment]
Ajelin uuden käännöksen testeille ja siellä näyttäisi nyt toimivan kuten pitääkin.

**Comment by emta001** [comment]
Käännös korjauksen pitäisi nyt olla myös tuotannossa.

**Comment by ElinaUotila** [comment]
Jes, näyttää toimivan tuotannossa.
