### ISSUE TITLE
[Kehitysehdotus] Saisiko muutoksen Koha-popuptekstiin? Kun olemassa olevan asiakastiedon asiakastyypin vaihtaa, kysyy Koha-popup: Vaihda viestiasetukset oletukseksi tälle ryhmälle?

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#3]
### Kehitysehdotukseni

Kun olemassa olevan asiakastiedon asiakastyypin vaihtaa, kysyy Koha-popupissa: 
Vaihda viestiasetukset oletukseksi tälle ryhmälle?

Olisiko selkeämpää kysyä esim.
Vaihda asiakkaan viestiasetukset asiakastyypin oletusviestiarvoiksi?

![kuva](https://user-images.githubusercontent.com/99952449/199447180-05307e7f-1bf5-425d-ad57-6f02c1afd703.png)

### Kohan osio

Asiakastiedot

**Comment by AnneliO** [comment]
Käännökset näkyvät nyt tuotannossa. Suljen tiketin.

**Comment by AnneliO** [comment]
Tämä käännös on kadonnut jonnekin, joten teen muutoksen uudelleen.

**Comment by Kati-Helle** [comment]
Helle-testissä ok: Vaihda asiakkaan viestiasetukset asiakastyypin oletusarvoiksi?
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/8f7fb2a7-816f-4a7c-b96b-921c0f38a9ff)

Sen sijaan Helle-tuotannossa edelleen: Vaihda viestiasetukset oletusasetukseksi tälle ryhmälle?
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/d36b2d4d-0c03-420b-8177-9e03ee2425aa)

(Liittyen Koha-päivitykseen 19.9.2023)

**Comment by AnneliO** [comment]
Koitatko päivittää sivun ja sitten testata uudelleen? Mulla tuli myös ensin väärä käännös näkyville, mutta tilanne korjautui sivun päivityksellä. :)

**Comment by Kati-Helle** [comment]
Jep, sivupäivitys auttoi. Kiitos Anneli vinkistä :)

Käännösmuutos on nyt myös tuotannossa (Koha-päivitys 19.9.2023).

**Comment by AnneliO** [comment]
Tämä käännös katosi versionvaihdon yhteydessä, koska sitä ei ollut yhteisössä eikä meidän dokumentaatiossa ylhäällä omana muutoksena.

Tein muutoksen nyt uudelleen sekä meidän messages-js-tiedostoon että yhteisön Weblateen. Se on nyt muodossa:

Change messaging preferences to default for this category?
_Vaihdetaanko asiakkaan viestiasetukset asiakastyypin oletusarvoiksi? Valitse Peruuta, jos haluat säilyttää nykyiset valinnat._

Muutos tulee tuotantoon seuraavassa päivityksessä.

**Comment by Kati-Helle** [comment]
Helle-Kohassa ei muutosta 3.12.2024 tehdyn Koha-päivityksen jälkeen

![kuva](https://github.com/user-attachments/assets/deb9d1ae-6148-44f3-91a5-daf8866ad84d)

**Comment by pknuuti** [comment]
Sama näkymä Vaarassa, kunnes päivitin näytön. Toimii oikein.

**Comment by Kati-Helle** [comment]
Monen näytön päivityksen ja eri asiakastiedoilla testauksen jälkeen sain minäkin uuden tekstin vihdoin näkyville 

![kuva](https://github.com/user-attachments/assets/d00139e4-44c9-439b-a402-2cd55fb90329)

Suljen tiketin.
