### ISSUE TITLE
Käännösmuutostoive: tietueen pääsivulla olevan "viesti virkailijalle" voisi yhtenäistää samaan muotoon kuin niteen muokkauksessa oleva "huomautus virkailijalle"

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha-translations#30]
### Tukipyyntö

Kohassa tietueen pääsivulla on sarake "Viesti virkailijalle", mutta niteen muokkauksessa saman kentän nimi on "Huomautus virkailijalle". Keskustelimme tästä pääkäyttäjäryhmässä ja tulimme siihen tulokseen, että molemmissa voisi mieluummin olla käännöksenä "huomautus virkailijalle".

**Comment by AnneliO** [comment]
Muutos tehty sekä meidän käännöstiedostoihin että yhteisön käännöstiedostoihin.
