### ISSUE TITLE
Käännösmuutostoive: asiakastietojen yhteenvedon alaotsikko Odottavat varaukset

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha-translations#31]
### Tukipyyntö

Asiakasnäkymästä voi tulostaa asiakastietojen yhteenvedon (Tulosta -> Asiakastietojen yhteenveto), https://vaara.koha-suomi.fi/cgi-bin/koha/members/summary-print.pl? Siinä on listattu myös asiakkaan varaukset. Englanniksi niitten yllä on otsikkona Pending holds, suomeksi kuittiin tulostuu Odottavat varaukset. Se on hiukan harhaanjohtava, koska listaus kattaa kaikki asiakkaan varaukset (voimassa, keskeytetty, noudettavissa olevat).

**Comment by AnneliO** [comment]
Tuolle tekstille löytyy oma "stringinsä" käännöstiedostosta, joten se voidaan kyllä muuttaa. Mutta mikä olisi hyvä, selkeä otsikko? Ihan vain "Varaukset"?

**Comment by IrinaHalminen** [comment]
Sopii! :)

**Comment by AnneliO** [comment]
Tämä on nyt tuotannossa, joten tiketin voinee sulkea. :)
