### ISSUE TITLE
Tietueiden eräpoisto: toiminnon käynnistyksen jälkeen ilmestyvässä ilmoituksessa mainitaan mm. Uusi niteiden poisto eräajona

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#34]
### Mikä vikana?

Tietueiden eräpoisto -toiminnon käynnistämisen jälkeen Koha ilmoittaa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/624b592a-5dcf-408a-9f30-94a2bbec7666)

englanniksi
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/c632954f-bfab-4726-8a71-536dbfbeed2e)

Suomenkielisessä ilmoituksessa mainitaan virheellisesti niteistä
Uusi niteiden poisto eräajona

Englanninkielisessä mainitaan tietueista
New batch record deletion

**Comment by AnneliO** [comment]
New batch record deletion -lause oli käännetty taustatöissä muotoon Uusi niteiden poisto eräajona. Se on nyt muutettu Koha-Suomen käännöksissä sekä yhteisön Weblatessa muotoon Uusi tietueiden poisto eräajona.

**Comment by Kati-Helle** [comment]
Kiitos Anneli :)
Tuleeko Koha-Suomen käännösmuutos käyttöön myöhemmin?

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/4c060f44-1e12-4315-8697-aebde4e91b03)

**Comment by AnneliO** [comment]
Tiketin tilana on Seuraavaan päivitykseen eli tulee tuotantoon ensi viikon päivityksessä. :)

**Comment by Kati-Helle** [comment]
Nyt päivityksen jälkeen kunnossa. Kiitos :)
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/d27ff783-0994-4caa-8698-5469d3d6d08f)
