### ISSUE TITLE
Käännösmuutos API-avaimet sivulle

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha-translations#35]
### Kehitysehdotukseni

API-avainten luonnissa käyttäjälle "Client ID" on suomennettu "Asiakkaan tunnus"  ja "Client secret"  "Avain". Nämä yhdessä muodostavata API-avaimet ja termit itse olisi ehkä viisasta jättää kokonaan kääntämättä.

Integroitavien järjestelmien toimittajat tajuavat mistä on kyse jos puhutaan Client ID:stä ja Client Secretistä, mutta eivät välttämättä tajua jos puhutaan asiakkaan tunnuksesta ja avaimesta.

Asiakkaan tunnus on lisäksi hieman monitulkintainen, koska sillähän voidaan periaatteessa viitata myös Kohan userid:hen/korttinumeroon.

**Comment by AnneliO** [comment]
Seuraavassa päivityksessä tulee seuraavanlaiset muutokset:

Client ID
Asiakkaan ID -> Client ID

Client ID:
Asiakkaan tunnus: -> Client ID:

Generate a new client id/key pair
Luo uusi asiakkaan id/avainpari -> Luo uusi client id/key -pari

Generate a new client id/secret pair
Luo uusi asiakkaan id/avainpari -> Luo uusi client id/secret -pari

Secret:
Avain: -> Secret:

**Comment by pirliis** [comment]
Tarkistin muutokset OUTIn tuotannosta ja testiltä. Näyttivät olevan oikein.

**Comment by AnneliO** [comment]
Muutos tuotannossa.
