### ISSUE TITLE
Käännösvirhe niteiden erämuokkauksessa jos poistettavia niteitä enemmän kuin mitä sallitaan näytettäväksi

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-translations#36]
### Mikä vikana?

Jos niteiden erämuokkaukseen vie muokattavaksi enemmän niteitä kuin mitä asetuksessa (MaxItemsToDisplayForBatchMod) on määritelty näytettäväksi, näytetään sivulla harhaanjohtava teksti: _Liian paljon niteitä (2002): Erässä voi muokata kerralla korkeintaan 1000 nidettä._ Teksti antaa ymmärtää ettei erämuokkausta voisi tehdä vaikka oikeasti kyse on siitä ettei niteitä voida näyttää.

Englanninkielinen lähdeteksti on _Too many items (2002): You are editing more than 1000 items in a batch, items will not be shown._

Niteiden eräpoistossa samaa kielikäännösongelmaa ei ole, siellä tulee teksti _Liian monta nidettä (2002) näytettäväksi. Tämä poistaa kaikki niteet._

**Comment by AnneliO** [comment]
Muutos tehty meidän tiedostoihin ja yhteisön Weblateen. Korjasin samalla toisen samaan paikkaan tulevan käännöksen:

Too many items (%s): You are editing more than %s items in a batch, items will not be shown.
Erässä voi muokata kerralla korkeintaan %s nidettä. -> Muokkaat yli %s nidettä erässä, niteitä ei näytetä.

Too many items (%s): You have edited more than %s items in a batch, items will not be shown.
Liian paljon niteitä (%s): Muokkaat yli %s nidettä erässä, niteitä ei näytetä. -> Liian paljon niteitä (%s): Olet muokannut yli %s nidettä erässä, niteitä ei näytetä.

Käännös päivittyy tuotantoon seuraavassa päivityksessä.

**Comment by ajrajala** [comment]
Muutokset tuotannossa, suljen tiketin.
