### ISSUE TITLE
Saisiko Kohan ilmoittamaan oikein niteen mahdollisen saatavuuden mm. hakutuloksen Rajoita saatavilla oleviin niteisiin -fasettirajauksella

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#37]
### Kehitysehdotukseni

Anneli Österman on maininnut tämän: Kohan logiikalla jokin on saatavana, kun sillä ei ole nidetaulussa merkintää onloan-sarakkeessa. Sama logiikka tiedonhaussa, kun rajaa saatavilla oleviin.
Maininta on keskustelusta, joka liittyi asetukseen AllowRenewalIfOtherItemsAvailable (Salli/Älä salli  asiakkaan uusia laina niteestä, josta on varauksia, jos vapaana on muita niteitä, jotka voivat täyttää varauksen.)

Saisiko niteen saatavilla-tietojen haun/tarkastelun toimimaan oikein?
Koha huomioisi myös ainakin reserves-taulun found-sarakkeen arvon (kuljetettavana T ja noudettavana W)? branchtransfers-taulun huomioiminen? Hankinnan nidetilan huomioiminen? 
Esimerkiksi kun tietueella on vain tilauksessa oleva/olevia niteitä, saa hakutuloksen Rajaa saatavilla oleviin niteisiin -fasettirajauksella teoksen, joilla on vain tilattuja niteitä kuten kuvassa
![kuva](https://user-images.githubusercontent.com/99952449/211513889-522a07d2-4948-4fd6-bd97-2b8d08821047.png)

**Comment by MikkoLiimatainen** [comment]
Yhteisössä on tiketti tähän asiaan liittyen: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=7012

Ilmeisesti ainakin reserves- ja branchtransfers-taulujen kanssa on se ongelma, etteivät niiden tiedot ole saatavilla hakumoottoreille, joten niitä ei voida käyttää tulosten suodattamiseen.

Tämä siis vaikuttaisi vaativan enemmänkin työtä, mutta olisi kyllä tarpeellinen kehitys.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 5.2.2024: Kuten kommenteissa on todettu, hakukone ei saa tietoja niteiden kuljetus- tai varaustiedoista, jolloin niitä ei voida höydyntää faseteissa. 

Muutetaan fasetin nimen käännös muotoon "Näytä niteet, jotka eivät ole lainassa". Kati pyytää helleläisiltä ruotsinkielisen käännöksen. Kati avaa yhteisöön tiketin, jossa pyydetään korjaamaan alkuperäinen teksti sellaiseen muotoon, että ei väitetä niteiden olevan saatavana, kun ne ei oikeasti ole sitä.

**Comment by Kati-Helle** [comment]
Ruotsinkielinen käännös helleläisiltä:
Visa de exemplar som inte är utlånade

**Comment by AnneliO** [comment]
Teksti oli muuttunut hieman uudempaan versioon ja se on nyt _Rajoita saatavilla oleviin niteisiin_. Se muuttuu muotoon _Rajoita vain niteisiin, jotka eivät ole lainassa_

Tähän liittyy myös käännös _Näytetään vain saatavilla olevat_, joka näytetään, kun ensin on klikattu _Rajoita saatavilla oleviin niteisiin_.  Jos käännöksen tekee samalla logiikalla kuin ylemmän, olisi se _Näytetään vain niteet, jotka eivät ole lainassa_.

Ruotsiksi tilanne on

_Visa bara tillgängliga exemplar_ -> _Visa de exemplar som inte är utlånade_
_Visa endast tillgängliga exemplar_ -> Mikä on tähän sopiva käännös?

**Comment by Kati-Helle** [comment]
Muuttuneeseen tilanteeseen helleläisten uusi ehdotus molempiin käännettäviin:

Visa bara tillgängliga exemplar -> Begränsa till de exemplar som inte är utlånade
Visa endast tillgängliga exemplar -> Visa endast de exemplar som inte är utlånade

**Comment by MikkoLiimatainen** [comment]
Kannattaisikohan tähän ehdottaa yhteisölle jonkinlaista on_shelf-saraketta items-tauluun?

Sarakkeessa voisi olla arvot 1 tai 0 sen mukaan onko nide hyllyssä vai ei. Jos nide lainataan, laitetaan kuljetukseen tai se tärppää varaukseen, laitettaisiin arvoksi 0, muutoin se olisi 1.

Olettaisin, että tällä päästäisiin eroon tuosta ongelmasta, ettei kuljetusten ja varausten tieto ole saatavilla hakumoottoreille. Ja kun tämä tieto yhdistetään muiden nidetietojen kanssa, niin pitäisi olla aika hyvin selvitettävissä, milloin nide oikeasti on hyllyssä ja saatavilla.

Toki tämä ei ole ihan yksinkertainen asia toteuttaa, mutta minusta kannattaisi jotenkin pyrkiä edistämään niteen todellisen saatavuuden saamista näkyviin Kohaan.

**Comment by AnneliO** [comment]
Showing only records with available items -> Visa endast de exemplar som inte är utlånade
Limit to records with available items -> Begränsa till de exemplar som inte är utlånade

**Comment by AnneliO** [comment]
Käännösmuutokset tulevat mukaan seuraavassa päivityksessä.

**Comment by Kati-Helle** [comment]
Kiitos, ruotsinkielinen käännösmuutos on nyt käytössä
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/d94c34d8-522f-4e82-acef-f7a8a6d43a0f)

Suomenkielinen ja englanninkielinen - nämä eivät ole vielä muuttuneet

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/b9e122a5-f41f-4e16-93e2-f27b53415362)

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/ab853c75-9028-49f3-afec-d3a65a9c61fc)

**Comment by AnneliO** [comment]
Suomenkieliset kuvittelin jo tehneeni aiemmin, mutta ilmeisesti olen unohtanut. Teen ne ensi viikon päivitykseen.

Englanninkieliseenhän tekstiin ei tule meidän tekemää muutosta, vaan jos sellainen joskus tulee, niin se tulee sitten yhteisöversion mukana. :)

**Comment by AnneliO** [comment]
Showing only records with available items -> Näytetään vain niteet, jotka eivät ole lainassa
Limit to records with available items -> Rajoita vain niteisiin, jotka eivät ole lainassa

Muutokset tulevat mukaan seuraavassa päivityksessä.

**Comment by Kati-Helle** [comment]
Hakutuloksen Saatavuus-fasetin tekstimuutos on nyt myös suomenkielisessä Kohassa
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/ef113f3a-2b8d-4b61-ae77-16c349514be7)

Samoin Saatavuus-fasetin tekstimuutos, joka seuraa Rajoita vain niteisiin, jotka eivät ole lainassa -fasetin klikkauksesta
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/b631bdda-6310-442b-bf05-f6f358b2fa6f)

**Comment by CodoDerDritte** [comment]
> Kannattaisikohan tähän ehdottaa yhteisölle jonkinlaista on_shelf-saraketta items-tauluun?
> 
> Sarakkeessa voisi olla arvot 1 tai 0 sen mukaan onko nide hyllyssä vai ei. Jos nide lainataan, laitetaan kuljetukseen tai se tärppää varaukseen, laitettaisiin arvoksi 0, muutoin se olisi 1.
> 
> Olettaisin, että tällä päästäisiin eroon tuosta ongelmasta, ettei kuljetusten ja varausten tieto ole saatavilla hakumoottoreille. Ja kun tämä tieto yhdistetään muiden nidetietojen kanssa, niin pitäisi olla aika hyvin selvitettävissä, milloin nide oikeasti on hyllyssä ja saatavilla.
> 
> Toki tämä ei ole ihan yksinkertainen asia toteuttaa, mutta minusta kannattaisi jotenkin pyrkiä edistämään niteen todellisen saatavuuden saamista näkyviin Kohaan.

Kannattaisi, ehdota :D Minusta tämä kuulostaa hyvältä ajatukseta. Nopeuttaisi luultavasti melkoisesti myös saatavuuslaskentaa.

**Comment by CodoDerDritte** [comment]
Tästä onkin näköjään jo toinenkin asiaan liittyvä tiketti: https://github.com/KohaSuomi/Koha/issues/1297
