### ISSUE TITLE
Tekstimuutosehdotus Kohan Lainaus- ja Tiedot -sivuille

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-translations#38]
### Kehitysehdotukseni

Voisiko Lainaus- ja Tiedot-sivuilla olevan asiakkaan maksuihin liittyvän lauseen muuttaa? 

![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/afb5e0e3-327c-40aa-bc28-b24a7e4e1b70)
Voisiko tämän muuttaa ->
"**Asiakkaalla on lainauskieltoon vaikuttavia maksuja €15.00.** Yhteensä (sis. maksut, jotka eivät vaikuta lainauskieltoon): €34.00.

### Jotain muuta?

Tällä hetkellä asiakkaan julkisoikeudellisista maksuista lukee Lainaus- ja Tiedot -sivuilla seuraavasti: 

Asiakkaalla on maksamattomia maksuja €15.00.  Yhteensä (sis. maksut, jotka eivät vaikuta lainauskieltoon): €34.00.

Ensimmäinen lause ei ole tarpeeksi informatiivinen, jos asiakkaalla on myös yksityisoikeudellisia maksuja, jotka eivät vaikuta lainauskieltoon. Asiakkaalla on tuolloin tiedoissaan kaksi eri summaa. Jos edellä mainittua lausetta hiukan muuttaa, niin siitä tulee ymmärrettävämpi.

**Comment by pknuuti** [comment]
Minusta tuo muutos selventäisi maksunäkymää, joten toivottavasti käännöksen voi muuttaa.

**Comment by lmstrand** [comment]
Huomioitava myös NoIssuesChargeGuarantees ja NoIssuesChargeGuarantorsWithGuarantees-asetukset.
(Tästä näkymästä puuttuu Koha-Suomi -muutos, jossa näytetään myös lainauskieltoon vaikuttamattomat maksut perässä.)

![image](https://github.com/KohaSuomi/Koha/assets/18394834/f6a80532-a2a1-4742-b8c3-3d2c775de159)

**Comment by AnneliO** [comment]
Seuraavassa päivityksessä tulee seuraavanlainen muutos:

Patron has outstanding charges of %s.
Asiakkaalla on maksamattomia maksuja %s. -> Asiakkaalla on lainauskieltoon vaikuttavia maksuja %s.

**Comment by pirliis** [comment]
Saisimmeko käännösmuutoksen myös testille?

**Comment by pirliis** [comment]
> Saisimmeko käännösmuutoksen myös testille?

OUTIn testillä uusi tekstimuutos näkyy oikein ja myös tuotannossa. Tosin, OUTIssa maksujen erottelu otetaan tuotannossa käyttöön 13.3.2024.

**Comment by piiaseme** [comment]
Tämä tehty. Suljen tiketin.
