### ISSUE TITLE
Käännösehdotus asiakkaan Lainaus-sivun poppariin, jossa näytetään yksityisoikeudellisten maksujen yhteissumma

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-translations#39]
Kun on käytössä maksujen erottelu julkis- ja yksityisoikeudellisiin maksuihin asiakkaan tiedoissa, tulee lainaustilanteessa tämä poppari, jossa näkyy asiakkaan yksityisoikeudellisten maksujen yhteissumma:
![image](https://github.com/KohaSuomi/Koha-translations/assets/98814860/bae21faf-1c4b-4193-9945-1d3c64b29a63)

Teksti popparissa on harhaan johtava. Voisiko poppariin muuttaa tekstiksi esim.:
"Asiakkaalla on maksamattomia maksuja, jotka eivät vaikuta lainauskieltoon: 17,00 €"

**Comment by pknuuti** [comment]
Vaarassa asiakkaan tiedoissa on näin: 
Maksut: Asiakkaalla on lainauskieltoon vaikuttavia maksuja €14,60. Yhteensä (sis. maksut, jotka eivät vaikuta lainakieltoon): €19,60.

**Comment by pirliis** [comment]
> Vaarassa asiakkaan tiedoissa on näin: Maksut: Asiakkaalla on lainauskieltoon vaikuttavia maksuja €14,60. Yhteensä (sis. maksut, jotka eivät vaikuta lainakieltoon): €19,60.

Myös OUTIssa on tuo sama teksti asiakkaan Lainaus- ja Tiedot-sivuilla, mutta lainaustilanteessa tulee vielä tuo sininen poppari.

**Comment by pknuuti** [comment]
Outoa. Vaarassa on lainaustilanteessa yksityisoikeudellisista maksuista näkyvissä vain huomautus maksuista (kuvassa)
![2023kuvat 342](https://github.com/KohaSuomi/Koha-translations/assets/73887264/e78ac883-f055-4c72-99a2-20ab26cd0c42)

Julkisoikeudellisista maksuista lainaustilanteessa tulee tieto, ettei asiakas voi lainata maksujen takia (lainauskieltoraja 15 euroa)
![2023kuvat 343](https://github.com/KohaSuomi/Koha-translations/assets/73887264/231cb360-efb8-4b81-9da0-ae726a95991b)

Vaarassa ei tule siis mitään poppareita lainaustilanteessa. Onko se joku asetus?

**Comment by pknuuti** [comment]
Olin väärässä tilanteessa. Vaarassakin tulee samanlainen poppari, mutta mielestäni teksti on väärin, koska nuohan ovat julkisoikeudellisia maksua mitä tuossa mainitaan. Teksti pitää muuttaa tai poppari piilottaa.
![2023kuvat 344](https://github.com/KohaSuomi/Koha-translations/assets/73887264/ff4b2357-a7a9-4b9a-8728-8b6529d424e3)

**Comment by AnneliO** [comment]
> Olin väärässä tilanteessa. Vaarassakin tulee samanlainen poppari, mutta mielestäni teksti on väärin, koska nuohan ovat julkisoikeudellisia maksua mitä tuossa mainitaan. Teksti pitää muuttaa tai poppari piilottaa. ![2023kuvat 344](https://private-user-images.githubusercontent.com/73887264/312407554-ff4b2357-a7a9-4b9a-8728-8b6529d424e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzI3NzMsIm5iZiI6MTcxMDMzMjQ3MywicGF0aCI6Ii83Mzg4NzI2NC8zMTI0MDc1NTQtZmY0YjIzNTctYTdhOS00YjlhLTg3MjgtOGI2NTI5ZDQyNGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEyMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZTcyYmYzYzI1NTIzNjgzYTI0N2RhMjk3N2VlNTY2OTY4MDM4ZDRjODY3ZDM0NjU0ODZjOTE1NjI2NWMyMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KtQDqjW-jvn3WaoahT2BI-G_KCPhRnXXh2E-sMaLC6U)

Tällä asiakkaalla näyttäisi olevan vain yksityisoikeudellisia maksuja. :)

**Comment by pknuuti** [comment]
> Tällä asiakkaalla näyttäisi olevan vain yksityisoikeudellisia maksuja. :)

Niin on, koska jos maksut ovat julkisoikeudellisia ja niitä on noin paljon, lainaaminen ei ole edes mahdollista.
![2023kuvat 345](https://github.com/KohaSuomi/Koha-translations/assets/73887264/ec6e3d9b-5a7d-48df-9a19-67f514c7e735)

Sen takia mielestäni tuo pop-upin teksti on harhaanjohtava.

**Comment by AnneliO** [comment]
Niin siis tarkoitit, että nykyisessä tekstissä mainitaan julkisoikeudellisia maksuja. Ymmärsin lauseen jotenkin väärin. :)

Alkuperäinen teksti on näin: *The patron has unpaid charges for holds, rentals etc of %s*

Varausmaksuja ja vuokriahan meillä ei ole, mutta ehkä tuon voisi hieman "väärin" kääntää vähän yleisempään muotoon kuin mainiten tiettyjä maksutyyppejä.

**Comment by pknuuti** [comment]
Paras ratkaisu on varmaankin kääntää tuo lause "väärin" yleisempään muotoon. Voisiko olla esimerkiksi "Asiakkaalla on maksamattomia maksuja xx euroa" eli ei eriteltäisi mitään erityisesti.

**Comment by AnneliO** [comment]
> Paras ratkaisu on varmaankin kääntää tuo lause "väärin" yleisempään muotoon. Voisiko olla esimerkiksi "Asiakkaalla on maksamattomia maksuja xx euroa" eli ei eriteltäisi mitään erityisesti.

Pirkko-Liisan kuvasta ei käy ilmi, mutta tuossa ilmoituksessa ei näy kaikki asiakkaan maksut. Vain tosiaan yksityisoikeudelliset maksut, joten minusta pelkkä "maksamattomia maksuja" jää liian epätarkaksi. Asiakkaalla voi olla myös julkisoikeudellisia maksuja tuon lisäksi.

**Comment by pknuuti** [comment]
Aivan, testasin nyt testiasiakkaallani, jolla näkyy molempia maksuja. Olisi parempi, jos tuon huomautuksen voisi piilottaa kokonaan, tai sitten siihen pitää lisätä oikeanlainen teksti, joka muodostuu helposti pitkäksi. Samalla näytöllä kuitenkin on nähtävissä asiakkaan maksuista huomautus.
![2023kuvat 346](https://github.com/KohaSuomi/Koha-translations/assets/73887264/91dee748-7720-462a-9c98-2f6ded81319d)

**Comment by atarnus** [comment]
Tuo elementti näyttäisi olevan jokin yleinen 'dialog message', joten sen piilottaminen ei varmaankaan onnistu CSS:llä ellei sitten samalla piilota kaikkia mahdollisia viestejä, joita tuohon saattaa kulloinkin tulla. JavaScriptillä onnistuisi. Ja tietysti koodimuutoksella circulation.tt:hen, mutta sitä tuskin kukaan pitää parhaana vaihtoehtona. 😃

**Comment by AnneliO** [comment]
The patron has unpaid charges for holds, rentals etc of %s

Asiakkaalla on maksamattomia maksuja varauksista, lainoista, tms: %s -> Asiakkaalla on maksamattomia maksuja, jotka eivät vaikuta lainauskieltoon: %s

**Comment by pirliis** [comment]
Tekstimuutos tuotu tuotantoon 21.5.2024. Suljen tiketin.
