### ISSUE TITLE
Käännökset: virhe hankinnan vastaanotossa

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha-translations#42]
### Mikä vikana?

Vastaanotettaessa niteitä Tilitystiedot-osiossa on englanniksi "Ordered by: Account has been deleted", suomeksi tällä hetkellä "Tilaaja: Tili on poistettu". Tili tarkoittaa käyttäjätiliä, joka pitäisi selventää suomennokseen.

**Comment by AnneliO** [comment]
Account has been deleted
Tili on poistettu -> Käyttäjätunnus on poistettu

Muutos tehty meidä omiin po-tiedostoihin ja yhteisön Weblateen. Tulee tuotantoon seuraavassa päivityksessä.
