### ISSUE TITLE
Varaushuomautuksen tekstit kummalliset

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha-translations#43]
### Mikä vikana?

Jos noutaa varauksen toisen puolesta, saa ilmoituksen:

![Vahvista lainaus](https://github.com/KohaSuomi/Koha/assets/99241432/cff5de44-fb5d-4628-ab71-416e4a994ff1)

Ilmoituksen tekstit ovat kuitenkin hassusti. Tulisi korjata.

### Mitä pitäisi tapahtua

Aiemmin näyttänyt tältä (kuvankaappaus Koha-ohjeesta 4.2.5)

![Vahvista lainaus - vanha](https://github.com/KohaSuomi/Koha/assets/99241432/2d7e35a2-10ac-479b-9c5e-69cdccd83369)

**Comment by AnneliO** [comment]
Nuo kaksi ilmoitusta näyttäisi olevan vähän eri tilanteesta. Toisessa varaus on käsiteltävänä-tilassa, joka tulee esim. silloin kun nide palautetaan noutokirjastossa automaattiin, mutta sitä ei ole vielä palautettu sen jälkeen Kohassa. Toisessa varaus on jo noudettavissa asiakkaalle.

Mutta käännös siinä on joka tapauksessa väärin. Se pitäisi olla jotain tyyliin "on käsittelyssä asiakkaalle x kirjastossa y". Miepä katson, saisiko tuosta järkevän lauseen aikaiseksi. :)

**Comment by AnneliO** [comment]
(%s) is being processed for 

(%s) käsitellään kirjastossa -> (%s) on käsiteltävänä asiakkaalle

**Comment by PiaKusmin** [comment]
Käännös näyttää hyvältä. Suljen tiketin.
