### ISSUE TITLE
Kori: Teoksia lisättäessä saatavassa ilmoituksessa tieto korin teosmäärästä menee sekaisin, jos koriin lisää teoksen perustiedot näytön kautta

### ISSUE THREAD

**Issue by VaisanRo** [KohaSuomi/Koha-translations#44]
### Mikä vikana?

Jos osakohteen lisää koriin perustiedot näytön kautta ja sen jälkeen lisää niteitä/osakohteita koriin suoraan hakutulosten kautta saa hieman hassun ilmoituksen. Esimerkiksi omassa korissa oli lisättynä 11 kohdetta. Koitin lisätä seuraavan osakohteen koriin perustiedot näytön kautta niin sain ilmoituksen "Tämä nide on lisätty koriisi". Kun lisäsin seuraavan osakohteen koriin taas hakutuloslistan kautta tuli ilmoitus "1 teosta lisätty koriin". Tämän jälkeen kun lisäsi vielä toisen osakohteen hakutulosnäytön kautta tuli ilmoitus "1 teosta lisätty koriin 1 on jo korissasi" vaikka tässä kohtaa osakohteita/niteitä oli lisättynä koriin jo 14. Sinällään tuo ei vaikuta korin toimintaan kai mitenkään ja nuo uudet nappulat toimivat hyvin, tuo huomio tuli vain tuossa sivussa tehtyä.

### Mitä pitäisi tapahtua

Korin pitäisi aina koriin teoksia lisätessä antaa ilmoitus montako teosta kyseisellä lisäyskerralla on lisätty ja montako korissa oli jo ennestään lisättynä, riippumatta siitä lisätäänkö teokset hakutulos- vai perustiedot näytöltä.

### Kuinka toistaa ongelma/asia

1. Hae jotain teoksia ja lisää ne hakutuloslistalla koriin 
2. Saat esim. 2 teosta lisättyäsi ilmoituksen "2 teosta lisätty koriin".
3. Avaa hakutuloksista joku tietue ja lisää se koriin perustiedot näytön kautta.
4. Saat ilmoituksen "Tämä nide on lisätty koriisi"
5. Mene takaisin hakutuloksiin ja koita lisätä teos hakutulossivulta koriin.
6. Saat ilmoituksen "1 Teosta lisätty koriin"
7. Koita vielä tämän jälkeen lisätä teos hakutulossivulta koriin
8. Saat ilmoituksen "1 Teosta lisätty koriin 1 on jo korissasi"
9. Tässä kohtaa korikuvakkeen vieressä näkyy kuitenkin korissa olevien teosten todellinen määrä, eli tässä kohtaa 5

**Comment by atarnus** [comment]
Katsoin tätä nyt uudestaan, niin hoksasin että tämähän toimii ihan oikein. :smile: 

Viesti "1 on jo korissasi" ilmoittaa että se ei lisää sinne samaa teosta enää uudestaan. Eli jos olen valinnut 3 teosta, mutta yksi oli jo korissa, saan viestin 2 teosta lisätty koriin 1 on jo korissasi.

Aluksi käsitin tuon kuitenkin ihan samalla tavalla kuin sinäkin, joten onko tuo viesti tarpeeksi selkeä?

**Comment by VaisanRo** [comment]
Hei, no niimpä toimiikin. Tajusin tuon itse vain ensiksi väärin, pahoittelut sekaannuksesta. Tämän voi varmaan sulkea, kun tuo toimiikin ihan oikein ja kyllä nuo viestitkin käy nyt järkeen kun tajusi mitä niillä haettiin.

**Comment by AnneliO** [comment]
Miepä katson, saisiko tuota tekstiä selkeytettyä ihan pikkasen. Siirrän tiketin Koha-translation-tietovarantoon. :)

**Comment by AnneliO** [comment]
En kauheasti muutosta keksinyt, mutta muutin "on jo korissasi" muotoon "oli jo korissasi". Tein muutoksen yhteisön [24.05-version käännöksiin](https://translate.koha-community.org/translate/koha/24-05/messages-js/fi/?checksum=bd73816e762174d7). Tuon tiedoston Koha-translations-tietovarantoon ja ne asentuvat nexteillä seuraavassa buildissa.

**Comment by VaisanRo** [comment]
Hei, tuo selkeytti kiitos. Suljen tiketin.
