### ISSUE TITLE
Kohan itsepalvelutoiminnon Palautus-kentässä käännösvirhe

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-translations#45]
Kohan itsepalvelutoiminnossa Palautus-kentässä väärä teksti "Kirjastokortin numero". 
![image](https://github.com/KohaSuomi/Koha-translations/assets/98814860/d78ccc1b-54f5-4828-9b35-35bcda036a09)

Tekstinä pitäisi olla "Anna viivakoodi" tjs.

**Comment by AnneliO** [comment]
Tein muutoksen fi-FI-opac-bootstrap.po-tiedostoon. Tulee mukaan seuraavassa viikkopäivityksessä.

Please enter barcode:

Kirjastokortin numero: -> Lue viivakoodi:

**Comment by pirliis** [comment]
Oikea käännös tuotu tuotantoon 28.5.2024. Joten suljen tiketin.
