### ISSUE TITLE
Käännösmuutos hyllyvarausraporttiin

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha-translations#47]
### Kehitysehdotukseni

Hyllyvarausraportin "Varaus" tekstin (englanniksi "Hold at") voisi muuttaa muotoon "Nouto". Kentässä on varauksen noutopaikka.

**Comment by AnneliO** [comment]
Tuota samaa käännöstä käytetään returns.tt-tiedostossa tällaisessa yhteydessä:

``` <h4><strong>Hold at</strong> [% Branches.GetName( destbranch ) %]</h4>```

Englanniksi
![kuva](https://github.com/user-attachments/assets/8076ef58-7c20-4c2b-bc46-8568ac3261e7)

Suomeksi
![kuva](https://github.com/user-attachments/assets/66474b2f-47cf-42ca-82f5-44ae20462683)

Suomeksi sanalla Nouto
![kuva](https://github.com/user-attachments/assets/0e9ec435-9c8f-4880-8e40-814f8b27bbbb)

Ei tuo taida olla sen huonompi vaihtoehto tuohon poppariin kuin sana Varauskaan?

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 3.12.2024: Kokeillaan sanaa "Noutopaikka".

**Comment by AnneliO** [comment]
Tehty muutos staff-prog-tiedostoon

Hold at
Varaus -> Noutopaikka

Muutos tulee tuotantoon seuraavassa päivityksessä.

**Comment by AnneliO** [comment]
Hyllyvarausraportilla Noutopaikka näyttää minusta ihan ok:lta:
![Image](https://github.com/user-attachments/assets/2b99d4d9-ac5c-4fe6-b268-4ceafa4ab752)

Myös varauksesta ilmoittavassa popparissa tieto on minusta ihan hyvä:
![Image](https://github.com/user-attachments/assets/f52a65a9-7151-483d-bea4-06038f794603)
