### ISSUE TITLE
Ruotsinkielisen Kohan Hyllyvarausraportti-toimintoon otsikko ruotsiksi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#48]
### Mikä vikana?

Hyllyvarausraportti-toiminnossa otsikko on englanniksi ruotsinkielisessä Kohassa.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b39c7f24-52e8-4efc-9198-767813c48144)

Helle-ehdotukset ruotsinnokseen

Reservationer att plocka

tai pidempi

Lista med nya reservationer att plocka

**Comment by AnneliO** [comment]
Holds to pull reported on %s -> Reservationer att plocka %s

Muutos tulee mukaan seuraavassa päivityksessä.

**Comment by Kati-Helle** [comment]
Ruotsinkielisessä Kohassa ruotsinnos nyt paikallaan
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/e1e5e597-bf8d-4c48-a1ea-d095e87ac9be)
