### ISSUE TITLE
Tietueen varaukset -välilehden ruotsinnoksiin muutostarve

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#49]
### Mikä vikana?

Tietueen varaukset -välilehden ruotsinkielisen Kohan teksteihin muutosehdotukset:

Nidettä kuljetaan - Exemplaret är under transport till xxx
 
Nide on noudettavana - Exemplaret väntar på avhämtningen från xxx sedan xx.xx.xxxx.

Näyttökuvat Helle-Kohasta 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b8456474-c8bb-41e6-9e7b-10cfdc13271c)

**Comment by AnneliO** [comment]
Sellainen hoksautus, että kannattaa laittaa mielummin englanninkielinen vastine kuin suomenkielinen, niin minun on helpompi löytää ne käännöstiedostoista, koska niissä alkukielenä on englanti eikä suomi. :)

**Comment by Kati-Helle** [comment]
Nidettä kuljetaan - Item being transferred to xxx - Exemplaret är under transport till xxx

Nide on noudettavana - Item waiting at xxx since xx.xx.xxxx -  Exemplaret väntar på avhämtningen från xxx sedan xx.xx.xxxx

**Comment by AnneliO** [comment]
> Item being transferred to

Kiitos, heti löytyi paremmin. Meinas mennä hankalaksi löytää. :)

**Comment by AnneliO** [comment]
Muutokset tehty ja tulevat mukaan seuraavassa päivityksessä.

**Comment by Kati-Helle** [comment]
Kiitos, käännösmuutokset nyt käytössä
![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/a5e50e08-51e5-44d6-9374-652d95a81dda)
