### ISSUE TITLE
[Bugi] Hyllyvarausraportin päivitystarpeesta kertova ilmoitus ei käänny suomeksi

### ISSUE THREAD

**Issue by janPasi** [KohaSuomi/Koha-translations#5]
### Mikä vikana?

KohaSuomi/Koha#254 korjauksen jälkeen hyllyvarausraportin päivitystarpeesta kertova ilmoitus ei käänny suomeksi. Ongelma lienee se että lihavointi on tekstistä poistettu.

### Mitä pitäisi tapahtua

Tekstin "No items found. Please ask your system administrator to ensure that update-holds-to-pull.pl gets run regularily."

pitäisi kääntyä suomeksi

"Ei niteitä. Pyydä järjestelmänvalvojaa tarkistamaan, että update-holds-to-pull.pl ajetaan säännöllisesti."

### Kuinka toistaa ongelma/asia

1. Mene "Lainaus ja palautus" -> "Hyllyvaraukset" sellaisessa Koha-installaatiossa, jossa hyllyvarausraportin tausta-ajo ei ole käynnissä _ja_ jossa ei ole olemassaolevaa perl-storablea hyllyvarauksista (tämän kirjoitushetkellä esimerkiksi outi-test).
2. Kyseinen teksti näkyy myös suomenkielisillä templateilla englanniksi (ongelma koskenee myös ruotsin kieltä).
3. 

### Selain

```markdown
Mikä tahansa selain, kyseessä on .po -tiedostossa oleva ongelma.
```

**Comment by AnneliO** [comment]
Tämä korjaantui, kun po-tiedostot luotiin uudelleen viikon 3 päivitystä varten. Suljen tiketin.
