### ISSUE TITLE
Käännösmuutoksia (swe) itsepalvelutoimintoon

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#50]
### Mikä vikana?

Saisiko Hellen käännösmuutos-ehdotukset itsepalvelutoimintoon?

Tiedot kirjasin tyyliin:
englanninkielisessä Kohassa (tekstin sijainti)
ruotsinkielisessä Kohassa nyt -> ehdotus uudeksi ruotsinnokseksi

Helle-kirjastot/biblioteken/Libraries Self checkout system (kaikilla toiminnon näytöillä yläreunassa)
Helle-kirjastot/biblioteken/libraries självutlåningautomat -> Helle-kirjastot/biblioteken/libraries självutlåning 

Tai saako toiminnon nimen kielittäin niin, että suomenkielisessä on vain suomeksi, ruotsinkielisessä vain ruotsiksi, englanninkielisessä vain englanniksi?

Username (lainaus)
Användarnamn -> Bibliotekskort   

Password (lainaus)
Lösenord -> Pinkod 

Please enter barcode (palautus)
Please enter barcode -> Läs streckkoden 

Show your checkouts (lainaus tai lainojen uusinta)
Visa din utlån -> Dina lån 

Call number (lainaus tai lainojen uusinta)
Hyllsignatur -> Hyllplats 

Palautettu (palautus)
Palautettu -> Återlämnad

**Comment by AnneliO** [comment]
> Helle-kirjastot/biblioteken/Libraries Self checkout system (kaikilla toiminnon näytöillä yläreunassa) Helle-kirjastot/biblioteken/libraries självutlåningautomat -> Helle-kirjastot/biblioteken/libraries självutlåning
> 
> Tai saako toiminnon nimen kielittäin niin, että suomenkielisessä on vain suomeksi, ruotsinkielisessä vain ruotsiksi, englanninkielisessä vain englanniksi?
> 

Tuo tieto/teksti tulee suoraan järjestelmäasetuksesta LibraryName. En äkkiseltään hoksaa, miten tuo eriyttäminen olisi mahdollista toteuttaa.


Nämä alla olevat tekstimuutokset ovat sellaisia, että niitä ei kannata tehdä yhteisön käännöksiin. Eli ne on Koha-Suomen itse ylläpidettäviä sitten jatkossa. (Eikä minulla ole kyllä oikeuksiakaan muuttaa yhteisön ruotsinkielisiä tekstejä :) )

> Username (lainaus) Användarnamn -> Bibliotekskort

Ok

> Password (lainaus) Lösenord -> Pinkod

Ok

> Please enter barcode (palautus) Please enter barcode -> Läs streckkoden

Ok

> Show your checkouts (lainaus tai lainojen uusinta) Visa din utlån -> Dina lån

Ok
 
> Call number (lainaus tai lainojen uusinta) Hyllsignatur -> Hyllplats

Ok
 
> Palautettu (palautus) Palautettu -> Återlämnad

En löydä tällaista käännöksistä. Teetkö tästä erillisen tiketin sellaisena, että tuo termi ei ole käännettävissä ja pitäisi saada kääntymään?

**Comment by Kati-Helle** [comment]
Kiitos muutoksista. 
Muuttumatta jäivät:

Password (lainaus)
Lösenord -> Pinkod
![kuva](https://github.com/user-attachments/assets/59ba78c1-e64e-4e88-b634-c1e3584ee804)

Palautettu (palautus)
Palautettu -> Återlämnad
![kuva](https://github.com/user-attachments/assets/912bd8e5-5909-4626-9ded-248f2f896af3)

**Comment by AnneliO** [comment]
> Kiitos muutoksista. Muuttumatta jäivät:
> 
> Password (lainaus) Lösenord -> Pinkod ![kuva](https://private-user-images.githubusercontent.com/99952449/362191986-59ba78c1-e64e-4e88-b634-c1e3584ee804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzU2MDcsIm5iZiI6MTcyNDgzNTMwNywicGF0aCI6Ii85OTk1MjQ0OS8zNjIxOTE5ODYtNTliYTc4YzEtZTY0ZS00ZTg4LWI2MzQtYzFlMzU4NGVlODA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMmIzOTkwZDIwNmU3M2QwOWE3MzFkMTNjMWM1ZWRjMjlmNmQwZjc0MmQ5ODQ3NmI4YWQzMGRiYTk4YjQ4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNyaset0-p0ZPNM__yTpk5oPZZcZavzEAVLpkbZr4Gs)
> 

Tälle löytyikin vielä yksi käännettävä teksti, ilmeisesti aiempi käännös ei "osunut" juuri tähän kohtaan. Vien uuden tiedoston kohta tietovarantoon ja se tulee käyttöön seuraavassa päivityksessä.

> Palautettu (palautus) Palautettu -> Återlämnad ![kuva](https://private-user-images.githubusercontent.com/99952449/362191237-912bd8e5-5909-4626-9ded-248f2f896af3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzU2MDcsIm5iZiI6MTcyNDgzNTMwNywicGF0aCI6Ii85OTk1MjQ0OS8zNjIxOTEyMzctOTEyYmQ4ZTUtNTkwOS00NjI2LTlkZWQtMjQ4ZjJmODk2YWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjAwZWI5ZWViNWIwOGE3YWM4MDY3YTVlYTQyNDAwMzE4ZDA3M2VlMDU2ZGNiMWRmMWI3MTk5YjI2MGRmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y3utFiOJCt8VP9Yu6G_3M3fx7__mtfHAiROmoLOUvmk)

Edellisestä kommentistani poimittu:

    Palautettu (palautus) Palautettu -> Återlämnad

En löydä tällaista käännöksistä. Teetkö tästä erillisen tiketin sellaisena, että tuo termi ei ole käännettävissä ja pitäisi saada kääntymään?

**Comment by AnneliO** [comment]
Oliko tässä vielä jotain keskeneräistä?

**Comment by Kati-Helle** [comment]
Näyttökuva Hellen tuotannosta. 

Låna ut -boxi
- Bibliotekskort-arvo on muuttunut arvoksi Inloggning. 
   Ehdotettu arvo Bibliotekskort on jo ollut käytössä (vastaava arvo englanninkielisessä Kohassa Login)
- käyttöön ehdotettu Pinkod on nyt käytössä. Kiitos.

![Image](https://github.com/user-attachments/assets/5ad941bb-684b-4ab0-96dc-f0610e4681d8)

**Comment by AnneliO** [comment]
Jahas, yritin kyllä tehdä version 24.05 käännöksiin kaikki samat muutokset kuin aiemminkin, mutta jokin on nyt ohittanut tutkan. Pitää tutkia.

**Comment by AnneliO** [comment]
Tehty muutos opac-bootstrap-tiedostoon:

Login:
Inloggning: -> Bibliotekskort:

Tulee tuotantoon seuraavassa päivityksessä.

**Comment by Kati-Helle** [comment]
Låna ut -boxissa on nyt ehdotettu käännös
Bibliotekskort

![kuva](https://github.com/user-attachments/assets/4e327c75-2311-4c70-8211-7b21a2a67f87)

Suljen tiketin.
