### ISSUE TITLE
Käännökset kadonneet joiltain arvoilta tietueen perustiedot-näytöltä

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-translations#54]
### Mikä vikana?

Outin tuotannossa ja Tätissä näkyy joidenkin vähän "harvinaisempien" arvojen nimet vain englanniksi tietueen perusnäytöllä, esim.

Outi:
![image](https://github.com/user-attachments/assets/de969206-71d1-417f-bc53-67f9b0abd1f9)

Täti:
![image](https://github.com/user-attachments/assets/021ae303-1ab4-4f3f-a6da-c09b513ed81b)

Suomi ja ruotsi molemmat puuttuvat.

**Comment by AnneliO** [comment]
Tää johtuu siitä, että olen onnistunut tuomaan viimeisimmässä [fi-FI-marc-MARC21.po](https://github.com/KohaSuomi/Koha-translations/commit/2f10fde5d589ee63b20b06503ac28e8d9d479df3#diff-6fba5a7ade80735cd779f196a665625897ec7e3dac2d9930a3274d9b06e8a21f) -tiedoston päivityksessä sellaisen version, josta puuttuu Koha-Suomi-muutokset. En nyt tiedä, miten siinä onnistuin, mutta lahjakas olen ollut. :) Selvittelen kehittäjiltä, miten tämän kanssa kannattaisi edetä.

**Comment by AnneliO** [comment]
Kodo revertoi minun aiemman tiedoston ja tein muutokset uudestaan oikeaan versioon suomenkielisestä tiedostosta. Vein sen nyt 23.xx-branchiin ja muutokset tulevat voimaan seuraavassa päivityksessä.

Ruotsinkielisistä käännöstiedostoista on puuttunut jo ennestään nuo samaiset käännökset, koska minun ruotsinkielen taito ei ole riittävä tekemään niitä ja en ole ainakaan vielä saanut muualta ehdotuksia hyviksi ruotsinnoksiksi niille. :)
