### ISSUE TITLE
Hyllypaikka vaihtuu palauttaessa - saisiko suomenkieliseen popupiin pienen muutoksen

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#55]
Kun hyllypaikka vaihtuu palauttaessa, ilmoittaa suomenkielinen Koha popupissaan mm. :

Niteen hyllypaikka päivitetty.
Vanha arvo: Aikuiset, näyttelyssä
Uusi tila: Aikuiset 

Popupissa mainitaan Uusi tila.
Saisiko muutoksen: Uusi tila -> Uusi arvo

Englanninkielisessä: New value
Ruotsinkielisessä: Nytt värde

![kuva](https://github.com/user-attachments/assets/149967ca-8d02-4dda-a9ee-bae033267c0c)

**Comment by AnneliO** [comment]
Muutos tehty yhteisön käännöksin Weblatesta. Tuon uudet käännökset Koha-translations-tietovarantoon ja ne tulee käyttöön, kun seuraavan kerran tehdään nexteillä build.

**Comment by ajrajala** [comment]
Vaski-testillä kurkkasin ja siellä käännösmuutos (Uusi arvo) ainakin näkyy oikein:
![kuva](https://github.com/user-attachments/assets/69e43123-a2b6-4535-925c-dd95a92708f8)

**Comment by AnneliO** [comment]
Tämä pitäisi olla jo tuotannossakin mukana, koska siellä on samat käännökset kuin nexteillä ja testeillä.

**Comment by Kati-Helle** [comment]
Helle-testisstä muutos ok
![kuva](https://github.com/user-attachments/assets/2b6217c5-1bd8-4c50-8c19-2a467d3594ae)

**Comment by AnneliO** [comment]
Katsoitteko saman myös tuotannossa? :)

**Comment by ajrajala** [comment]
Meillä ei ole tuotannossa tuota hyllypaikan päivitystä vielä käytössä, mutta pystytkö Kati tsekkaamaan Hellen tuotannosta?

**Comment by Kati-Helle** [comment]
Helle-tuotannossa ominaisuus ei ole vielä käytössä. Lumme-kimpassa muistaakseni on?

**Comment by Kati-Helle** [comment]
Testasin Helle-tuotannossa sellaisen kirjaston 'avulla', joka ei ole aktiivikäytössä.

Muutos toimii myös tuotannossa
![kuva](https://github.com/user-attachments/assets/f9d411c9-cedf-4dde-8c4f-b54ed8ba1867)

Suljen tiketin.
