### ISSUE TITLE
Käännösmuutos Palautus-sivulle: Nidettä ei ole palautettu

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-translations#56]
### Tukipyyntö

Versiossa 24.05 kun palauttaa niteen, joka ei ollut lainassa, tulee nyt vielä teksti:
![image](https://github.com/user-attachments/assets/19da99b8-39fa-494e-837e-3fb58b8d8eaa)

Anneli lupasi muuttaa tekstin muotoon "Nidettä ei ole palautettu lainasta".

**Comment by AnneliO** [comment]
Muutos tehty yhteisön käännöksin Weblatesta. Tuon uudet käännökset Koha-translations-tietovarantoon ja ne tulee käyttöön, kun seuraavan kerran tehdään nexteillä build.

**Comment by AnneliO** [comment]
Nexteillä on tehty muutamankin kerran build, joten tämä muutos pitäisi nyt näkyä nexteillä.

**Comment by pirliis** [comment]
Tekstimuutos näkyy pyydetyllä tavalla:
![image](https://github.com/user-attachments/assets/86662798-79a3-45c3-b9e3-f6f97a446fe6)

Suljen tiketin.
