### ISSUE TITLE
Saisiko muutoksen popuptekstiin? Kun nide palauttaessa tärppää noudettavaksi varaukseen, lukee popupissa mm. Asiakasta ei ole huomautettu.

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-translations#6]
### Kehitysehdotukseni

Kun palautettu nide tärppää varaukseen noudettavaksi, lukee palautuksen popupissa mm. tämä: 
Asiakasta ei ole huomautettu.

![kuva](https://user-images.githubusercontent.com/99952449/203507301-006e5c80-9ceb-453f-8a41-f23d0197babb.png)

Saisiko Asiakasta ei ole huomautettu -tekstin vaihtoon? Tekstiehdotuksia:
Asiakkaalle ei ole ilmoitettu varauksesta. 
Asiakkaalle ei ole lähetetty noutoilmoitusta.
Asiakas ei ole saanut ilmoitusta noudettavasta varauksesta.

**Comment by AnneliO** [comment]
Hmm.. tuo teksti tulee, kun asiakkaalla ei ole valittuna viestiasetuksissa mitään vaihtoehtoa. Eli kun asiakkaalle ei lähde tekstiviestiä tai sähköpostia. Mutta silloin meillä lähtee asiakkaalle paperikirje, eli tieto ei sinänsä pidä paikkansa.

Käännöksessä voisi valehdella, että asiakkaalle lähtee paperikirje, mutta lähteekö kuitenkaan kaikissa tapauksissa, kaikissa Kohissa? Ja valehtelu on vähän rumaa.

Toki alkuperäinen käännöskään ei vastaa todellisuutta, kun asiakkaalle kuitenkin lähtee viesti jossain muodossa.

En muuta vielä tekstiä, pohditaan jotain hyvää ratkaisua. :)

**Comment by janPasi** [comment]
Jos laittaisi ihan rehellisesti että "Asiakkaan viestiasetuksia ei ole määritelty" ?

**Comment by Kati-Helle** [comment]
Olisiko popupin hyvä olla kertovampi/selittävämpi?
Asiakkaalle ei lähetetä tekstiviestiä eikä sähköpostiviestiä, koska asiakastiedon viestiasetuksia ei ole määritelty.
Asiakas ei saa tekstiviestiä eikä sähköpostiviestiä (asiakastiedon viestiasetukset puuttuvat).

**Comment by Kati-Helle** [comment]
Teksti samaan tyyliin kuin silloin, kun asiakkaan viestiasetuksissa on noutoilmoitus-määrittelyjä? Popup on tuolloin tämän tyylinen.
![kuva](https://user-images.githubusercontent.com/99952449/211752184-e45ffb61-9c9c-4017-b6e8-690ac1527866.png)

Teksti-ehdotus tuon perusteella:
Ilmoitus: Ei sähköpostia, ei tekstiviestiä (asiakastiedon viestiasetukset puuttuvat).

**Comment by ajrajala** [comment]
> Jos laittaisi ihan rehellisesti että "Asiakkaan viestiasetuksia ei ole määritelty" ?

Tämä kuulostaisi hyvältä lähestymistavalta, ehkä vielä hiukan tarkemmin "Asiakkaalla ei ole noutoilmoitustapaa valittuna" tms koska asiakkaalla voi kuitenkin olla osa viestiasetuksista ihan ok.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 26.2.2024: Muutetaan meidän omiin po-tiedostoihin muotoon

Ilmoitus: Kirje

Alkuperäisteksti: Patron is not notified

**Comment by AnneliO** [comment]
Seuraavaan päivitykseen tulee seuraavanlainen muutos:

Patron is not notified
Asiakasta ei ole huomautettu -> Ilmoitus: Kirje

**Comment by Kati-Helle** [comment]
Kirje on nyt paikallaan. 

![kuva](https://github.com/KohaSuomi/Koha-translations/assets/99952449/ad12a924-b3ea-40cd-90e8-808949dbcb61)
