### ISSUE TITLE
Lainahistoriassa termimuutos Aina -> Toistaiseksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-translations#9]
Koha-Suomen asiantuntijaryhmä kävi läpi tietojen säilytysajat ja siinä yhteydessä päätettiin muuttaa lainahistoria-toiminnossa Always-sanan käännökseksi "Toistaiseksi" nykyisen "Aina" sijaan. Emme voi taata, että lainahistoria säilyy ainiaan.

[Tietojen säilytysajat](https://koha-suomi.fi/dokumentaatio/tietojensailytysajat/)

**Comment by AnneliO** [comment]
Always-sana olikin Forever. Sen käännös on nyt muutettu muotoon Toistaiseksi sekä meidän tiedostoihin että yhteisön käännöksiin.

**Comment by CodoDerDritte** [comment]
Käännökset päivitetty.

**Comment by AnneliO** [comment]
Kiitos!
